apiVersion: v1
kind: ConfigMap
metadata:
  name: streamsafe-config
  namespace: default
data:
  # Ingestion Settings
  TWITCH_CHANNEL: Jynxzi
  CHANNEL_NAME: Jynxzi
  TWITCH_IRC_URL: wss://irc-ws.chat.twitch.tv:443
  
  # Connection Settings
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BROKER: kafka:9092
  MODERATION_TOPIC: chat_events