name: Build & Push (Placeholder)

# This tells GitHub to run this script on every push to 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Placeholder Step
        run: echo "Docker build pipeline is initialized. Waiting for AWS configuration in Week 4."